const SearchResults = () => {
  return (
    <>
      {/* == Search Results & Cards == */}
      <h2
        className='mb-8 hidden text-center text-2xl font-semibold'
        id='search-result-title'
      >
        {/* Recipe Ideas for Your Search: */}
      </h2>
      <div
        className='error text-clamp-10-12 hidden text-center font-normal text-white sm:text-red-500'
        id='error'
      >
        {/* Error message */}
      </div>
      {/* Search results Cards */}
      <div
        className='search-results flex flex-row flex-wrap justify-evenly gap-6'
        id='search-results'
      >
        {/* Generated based on search results (stored in ./src/js/app.js) */}
      </div>
      {/* Modal */}
      <div
        id='details-modal'
        tabIndex={-1}
        className='fixed top-0 left-0 right-0 z-50 hidden h-full w-full overflow-y-auto overflow-x-hidden p-4 md:inset-0'
        role='dialog'
        style={{ alignItems: 'flex-start' }}
      >
        <div className='relative h-full w-full max-w-4xl md:h-auto'>
          {/* Modal content autogenerated based on selected meal (stored in ./src/js/app.js)  */}
        </div>
      </div>
      <div
        className='overlay fixed inset-0 z-40 hidden h-full w-full bg-slate-900 opacity-90'
        id='overlay'
      />
    </>
  );
};

export default SearchResults;
