import { useState, useEffect } from 'react';

// type Recipe = {
//   id: number;
//   name: string;
//   category: string;
//   image: string;
//   instructions: string;
// };

const SearchResults = () => {
  // const [searchQuery, setSearchQuery] = useState<string>('');
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);

  const handleOpenModal = (): void => {
    setIsModalOpen(true);
  };

  const handleCloseModal = (): void => {
    setIsModalOpen(false);
  };

  return (
    <>
      {/* == Search Results & Cards == */}
      <h2
        className='mb-8 text-center text-2xl font-semibold'
        id='search-result-title'
      >
        Recipe Ideas for searchQuery:
      </h2>
      <div
        className='error text-clamp-10-12 hidden text-center font-normal text-white sm:text-red-500'
        id='error'
      >
        Recipe not found
        {/* Error message */}
      </div>
      <div
        className='search-results flex flex-row flex-wrap justify-evenly gap-6'
        id='search-results'
      >
        {/* Search Results */}
        <div className='card w-sm mx-auto mb-4 max-w-full border-spacing-4 rounded-lg border border-gray-700 bg-gray-800 shadow'>
          <div className='card-img-container rounded'>
            <img
              className='rounded-t-lg object-cover'
              src='https://unsplash.it/700/700'
              alt='card image showing recipe preview'
            />
          </div>
          <div className='p-5'>
            <h5 className='mb-2 text-center text-xl font-medium text-white'>
              Recipe Name
            </h5>
            <div className='flex w-full items-center justify-center'>
              <button
                className='recipe-btn mt-4 inline-flex items-center rounded-lg  bg-amber-500 px-3 py-2 text-center text-sm font-medium text-slate-900 transition duration-300 ease-in-out hover:bg-amber-600 focus:outline-none focus:ring-4 focus:ring-amber-400 active:bg-amber-700'
                id='recipe-btn'
                key='1'
                type='button'
                onClick={handleOpenModal}
              >
                Recipe Details 🍲
              </button>
            </div>
          </div>
        </div>
      </div>
      {/* Modal */}
      {isModalOpen && (
        <div>
          <div
            id='details-modal'
            tabIndex={-1}
            className='fixed top-0 left-0 right-0 z-50 flex h-full w-full justify-center overflow-y-auto overflow-x-hidden p-4 md:inset-0'
            role='dialog'
          >
            <div className='relative h-full w-full max-w-4xl md:h-auto'>
              {/* Modal content autogenerated based on selected meal */}
              <div className='relative mx-auto max-w-4xl rounded-lg bg-gray-700'>
                {/* Modal header */}
                <div className='flex items-center justify-between rounded-t border-b border-gray-600 p-5'>
                  <h3
                    className='text-clamp-12-17 font-medium capitalize text-white'
                    id='modal-recipe-title'
                  >
                    Recipe Name 🥘
                  </h3>
                  <button
                    type='button'
                    id='close-btn'
                    className='ml-auto inline-flex items-center rounded-lg bg-transparent p-1.5 text-sm text-gray-400 hover:bg-gray-600 hover:text-white'
                    onClick={handleCloseModal}
                  >
                    <svg
                      aria-hidden='true'
                      className='h-5 w-5'
                      fill='currentColor'
                      viewBox='0 0 20 20'
                      xmlns='http://www.w3.org/2000/svg'
                    >
                      <path
                        fillRule='evenodd'
                        d='M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z'
                        clipRule='evenodd'
                      />
                    </svg>
                    <span className='sr-only'>Close modal</span>
                  </button>
                </div>
                {/* Modal body */}
                <div className='space-y-6 p-6'>
                  <div className='flex flex-wrap items-center justify-between gap-4'>
                    <h3 className='text-clamp-12-17'>
                      Recipe Preparation 📝🍳
                    </h3>
                    <div className='rounded border px-4 py-0.5 md:px-8'>
                      <span
                        className='text-center text-sm font-semibold text-white'
                        id='modal-recipe-category'
                      >
                        🍽️ Recipe Category
                      </span>
                    </div>
                  </div>
                  <p
                    className='text-sm leading-relaxed text-gray-400 md:text-base'
                    id='modal-preparation-instructions'
                  >
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Repudiandae ipsa ut fugiat et, quam repellat cupiditate,
                    esse eos architecto, veniam quos iure ex expedita fuga
                    officiis sunt? Ipsum perferendis non fugiat maiores
                    exercitationem quo nesciunt eos quod quia rerum. In et
                    laborum optio eveniet ex veniam quis quidem, voluptatum
                    omnis quo exercitationem, praesentium necessitatibus quasi
                    magni accusamus amet tempora, atque aut itaque obcaecati
                    voluptatem pariatur. Explicabo minima vitae totam laudantium
                    adipisci dolores qui minus itaque, obcaecati quae rem animi
                    natus earum sapiente iure asperiores magnam tempora cumque
                    id odio sed? Recusandae corporis incidunt consectetur odit
                    expedita autem ducimus eaque cupiditate corrupti sunt. Eum
                    consequatur officiis, dolor est provident maxime, excepturi
                    odio, sequi illo quisquam laborum vitae. Animi dolor vitae
                    beatae nemo quis sequi incidunt accusantium magni iste
                    dolore quisquam consequatur dolores voluptates ea est vel,
                    quo nostrum libero ipsa eos a, similique possimus deserunt
                    ducimus? Molestias blanditiis necessitatibus quasi nisi
                    dolores rerum quod molestiae, et tempora, libero quos quia.
                    Deleniti soluta expedita labore commodi aliquid consequuntur
                    voluptatem, placeat dolor voluptatibus? Voluptatum beatae
                    sapiente non harum, reprehenderit expedita molestiae,
                    excepturi voluptatibus, eius repellendus hic aut? Tenetur
                    amet, perferendis laboriosam nihil qui iusto quos ut
                    temporibus beatae? Ab quisquam earum magnam inventore?
                  </p>
                </div>
                {/* Modal footer */}
                <div className='flex flex-col items-center gap-8 space-x-2 rounded-b border-t border-gray-600 p-6'>
                  <h3 className='text-clamp-12-17 text-center'>
                    Recipe Tutorial Video 🎥👨‍🍳
                  </h3>
                  <div className='h-full w-full'>
                    <iframe
                      id='modal-yt-video'
                      className='video-embed mx-auto'
                      src='https://www.youtube.com/embed/HYSspU4XhC4'
                      title='Recipe Tutorial Video'
                      allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
                      allowFullScreen
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* <div
            className='overlay fixed inset-0 z-40 h-full w-full bg-slate-900 opacity-90'
            id='overlay'
          /> */}
        </div>
      )}
    </>
  );
};

export default SearchResults;
